- hosts: localhost
  become: true
  pre_tasks:
  - name: Update repositories
    pacman:
      update_cache: yes
      changed_when: false
  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml